// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSSIONS: KVNamespace;
	RESEND_API_KEY: string;
	RESEND_FROM_EMAIL: string;
	JWT_SECRET: string;
	GOOGLE_MAPS_API_KEY: string;
	DB: D1Database;
	ASSETS: Fetcher;
}
declare module "*.sql" {
	const value: string;
	export default value;
}